version: '3.8'


services:

  ###
  # Traefik Reverse Proxy
  ###
  traefik:
    image: traefik:v2.8.3
    restart: unless-stopped
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./configs/traefik/certs.yml:/etc/traefik/dynamic_conf/certs.yml
      - certs:/etc/certs

    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=sigdep3_hie'
      - 'traefik.http.routers.api.rule=Host(`test2.cihis.org`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api.entrypoints=web-secure'
    networks:
      - hie
    ports:
      - 80:80
      - 443:443

  sigdep3:
    image: partnersinhealth/openmrs-server:latest
    restart: unless-stopped
    depends_on:
      sigdep-db:
        condition: service_healthy
    container_name: sigdep3
    hostname: sigdep3
    environment:
      OMRS_CONFIG_CONNECTION_SERVER: "sigdep-db"
      OMRS_CONFIG_CONNECTION_ROOT_PASSWORD: "root"
      OMRS_CONFIG_CONNECTION_USERNAME: "root"
      OMRS_CONFIG_CONNECTION_PASSWORD: "root"
      OMRS_CONFIG_CONNECTION_EXTRA_ARGS: "&autoReconnect=true&sessionVariables=default_storage_engine%3DInnoDB&useUnicode=true&characterEncoding=UTF-8&useSSL=false&requireSSL=false"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "false"
      OMRS_CONFIG_CREATE_TABLES: "false"
      OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE: "true"
      OMRS_DEV_DEBUG_PORT: "1044"
    volumes:
      - ./configs/sigdep3/distribution:/openmrs/distribution
      # uncomment to persist the volumes on the Host file system
      #- .data/sigdep3:/openmrs/data
    networks:
      - hie
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=sigdep3_hie'
      - 'traefik.http.services.sigdep3.loadbalancer.server.port=8080'
      - 'traefik.http.services.sigdep3.loadbalancer.server.scheme=http'
      - 'traefik.http.routers.sigdep3.service=sigdep3'
      - 'traefik.http.routers.sigdep3.tls=true'
      - 'traefik.http.routers.sigdep3.entrypoints=web-secure'
      - 'traefik.http.routers.sigdep3.rule=Host(`test2.cihis.org`) && PathPrefix(`/openmrs`)'

  sigdep-db:
    image: library/mysql:5.6
    restart: unless-stopped    
    hostname: sigdep-db
    container_name: sigdep-db
    command: "mysqld \
              --character-set-server=utf8 \
              --collation-server=utf8_general_ci \
              --max_allowed_packet=1G \
              --default-authentication-plugin=mysql_native_password \
              --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: "openmrs"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./configs/sigdep3/mysql.cnf:/etc/mysql/conf.d/custom.cnf  # mysql config preconfigured to allow binlog/debezium
      - ./configs/sigdep3/init-db:/docker-entrypoint-initdb.d
    
      # uncomment to persist the volumes on the Host file system
      #- .db/sigdep3:/var/lib/mysql
    networks:
      - hie

#OpenHIM -IOL
  mongo:
    container_name: openhim-mongo
    ports:
      - "27017:27017"
    image: mongo:3.4
    networks:
      - hie
      
  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:v7.1.0
    restart: unless-stopped
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
    healthcheck:
      test: "node /healthcheck.js"
      interval: 20s
      timeout: 20s
      retries: 2
    volumes:
      - ./configs/openhim/healthcheck.js:/healthcheck.js
    depends_on:
      - mongo
    networks:
      - hie
    labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=sigdep3_hie'
        - 'traefik.http.services.openhim-api.loadbalancer.server.port=8080'
        - 'traefik.http.services.openhim-api.loadbalancer.server.scheme=https'
        - 'traefik.http.routers.openhim-api.service=openhim-api'
        - 'traefik.http.routers.openhim-api.tls=true'
        - 'traefik.http.routers.openhim-api.entrypoints=web-secure'
        - 'traefik.http.routers.openhim-api.rule=Host(`test2.cihis.org`) && PathPrefix(`/openhimcomms`)'
        - 'traefik.http.routers.openhim-api.middlewares=openhim-api'      
        - 'traefik.http.middlewares.openhim-api.stripprefix.prefixes=/openhimcomms'
        - 'traefik.http.middlewares.openhim-api.stripprefix.forceSlash=false'

        - 'traefik.http.services.openhim-ssl.loadbalancer.server.port=5000'
        - 'traefik.http.services.openhim-ssl.loadbalancer.server.scheme=https'
        - 'traefik.http.routers.openhim-ssl.service=openhim-ssl'
        - 'traefik.http.routers.openhim-ssl.tls=true'
        - 'traefik.http.routers.openhim-ssl.entrypoints=web-secure'
        - 'traefik.http.routers.openhim-ssl.rule=Host(`test2.cihis.org`) && PathPrefix(`/openhimcore`)'
        - 'traefik.http.routers.openhim-ssl.middlewares=openhim-ssl'      
        - 'traefik.http.middlewares.openhim-ssl.stripprefix.prefixes=/openhimcore'
        - 'traefik.http.middlewares.openhim-ssl.stripprefix.forceSlash=false'

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:v1.15.0
    volumes:
      - ./configs/openhim-console/default-local.json:/usr/share/nginx/html/config/default.json
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 10s
      timeout: 60s
      retries: 3
    labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=sigdep3_hie'
        - 'traefik.http.services.openhim-console.loadbalancer.server.port=80'
        - 'traefik.http.services.openhim-console.loadbalancer.server.scheme=http'
        - 'traefik.http.routers.openhim-console.service=openhim-console'
        - 'traefik.http.routers.openhim-console.tls=true'
        - 'traefik.http.routers.openhim-console.entrypoints=web-secure'
        - 'traefik.http.routers.openhim-console.rule=Host(`test2.cihis.org`)'
    networks:
      - hie

  # Loads Default OpenHIM Config
  openhim-config:
    container_name: openhim-config
    image: ghcr.io/i-tech-uw/openhim-config:v0.0.0
    volumes:
      - ./configs/openhim/test-openhim-config.json:/app/test-openhim-config.json
    networks:
      - hie

###
  # OpenCR - Client Registry
  ###
  opencr:
    container_name: opencr
    hostname: opencr
    image: intrahealth/opencr:local
    restart: unless-stopped
    environment:
      - NODE_ENV=docker
      - HAPI_FHIR_URL=http://opencr-fhir:8080/fhir/metadata
    volumes:
      - ./configs/opencr/config.json:/src/server/config/config_docker.json
      - ./configs/opencr/mediator.json:/src/server/config/mediator.json
      - ./configs/opencr/decisionRules.json:/src/server/config/decisionRules.json
      - ./configs/opencr/PatientRelationship.json:/src/resources/Relationships/PatientRelationship.json
    depends_on:
      - opencr-fhir
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=sigdep3_hie'
      - 'traefik.http.routers.opencr.tls=true'
      - 'traefik.http.routers.opencr.entrypoints=web-secure'
      - 'traefik.http.services.opencr.loadbalancer.server.port=3000'
      - 'traefik.http.routers.opencr.rule=Host(`test2.cihis.org`) && PathPrefix(`/crux`) || PathPrefix(`/ocrux`)' 
      - 'traefik.http.services.opencr.loadbalancer.server.scheme=http'
      - 'traefik.http.routers.opencr.service=opencr'
    networks:
      - hie


  opencr-fhir:
    image: hapiproject/hapi:v5.1.0
    container_name: opencr-fhir
    hostname: opencr-fhir
    restart: unless-stopped
    healthcheck:
      test: "curl -sS http://opencr-fhir:8080/fhir/metadata || exit 1"
      interval: 90s
      timeout: 30s
      retries: 3
    volumes:
      - /data/hapi
    #   - ./configs/opencr/application.yml:/data/hapi/application.yaml
    ports:
      - 8081:8080
    # env_file:
    #   - ./configs/opencr/.env
    # environment:
    #   SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
    networks:
      - hie
  es:
    container_name: es
    hostname: es
    image: intrahealth/elasticsearch:latest
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /usr/share/elasticsearch/data
    healthcheck:
      test: "curl --silent --fail http://es:9200/_cluster/health || exit 1"
    networks:
      - hie

 
secrets:
  datasource.password:
    file: ./configs/openelis/properties/datasource.password
  common.properties:
    file: ./configs/openelis/properties/common.properties

volumes:
  db-data:
  key_trust-store-volume:
  certs-vol:
  certs:
  keys-vol:       

networks:
  hie:
